name: Python Sample Testing

on: push

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: SetUp Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run Test 
      run: |
        python -m pytest main.py
